version: '3'
services:
  database:
    image: "postgres:13" # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
volumes:
  postgres-data: # named volumes can be managed easier using docker-compose
